name: Deploy to production
on:
    push:
        branches: [ "main" ]

defaults:
    run:
        shell: bash
        working-directory: infra_website

jobs:
    pull:
        name: Pull sources
        runs-on: self-hosted
        steps:
            - name: pull
              run: git pull --rebase
    
    cleanup:
        needs: pull
        name: Cleanup
        runs-on: self-hosted
        steps:
            - name: cleanup
              run: rm -rf dist
        
    deploy:
        needs: cleanup
        name: Deploy (npm)
        runs-on: self-hosted
        steps:
            - name: Update dependencies
              run: npm i
            - name: Build
              run: npm run build
            